language: python

notifications:
  email: false


matrix:
  include:
    - os: linux
      python: "2.7"
      # Tell travis we want debian trusty
      sudo: required
      dist: trusty
      env:
        - TESTATTR="'not huge and not known_failing'"
      addons:
        apt:
          packages:
            - astyle
            - cppcheck
            - enchant

    - os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - TESTATTR="'not linux and not known_failing and not huge'"
      before_install:
        - source ci_scripts/install.sh

# command to install common dependencies
install:
  - python --version
  - which python
  - gcc --version
  - which gcc
  - make install-dependencies

# command to run tests
script:
  - make test
