language: python

notifications:
  email: false


matrix:
  include:
    - os: linux
      python: "2.7"
      # Tell travis we want debian trusty
      sudo: required
      dist: trusty
      env:
        - TESTATTR="'not huge and not known_failing'"
      addons:
        apt:
          packages:
            - astyle
            - cppcheck
            - enchant

    - os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - TESTATTR="'not linux and not known_failing and not huge'"
      before_install:
        - source ci_scripts/install.sh

# command to install common dependencies
install:
  - python --version
  - which python
  - gcc --version
  - which gcc
  - make install-dependencies

# command to run tests
script:
  - make test
  # coverage needs a clean build, generate coverage for all ARCHs
  # running it here means it will fail the build if it fails
  - make clean coverage-gcovr.xml coverage.xml

# generate all the diagnostic reports
after_success:
  - make pylint
  - make pep8
  # do the docs build?
  - make doc
  # only upload the linux coverage report to codecov as it merges all reports
  # from all builds into one
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install codecov; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov -X pycov search gcov -f coverage.xml coverage-gcovr.xml; fi
